### ISSUE TITLE
Pre-Release pypi version

### ISSUE THREAD

**Issue by jbravo94** [senaite/senaite.diagnosis#1]
Dear maintainers,

i kindly ask for a pre-release version e.g. 0.0.dev0 on pypi to test senaite.diagnosis on installations because currently buildout complains that it does not find the version in the index.

Many thanks,
Johannes

**Comment by xispa** [comment]
Hi @jbravo94 we plan to do a first release of this add-on within the following weeks, after SENAITE 2.5.0. Will keep you informed

**Comment by jbravo94** [comment]
Alright - Thank you :)
