### ISSUE TITLE
Docs folder missing in buildout installation

### ISSUE THREAD

**Issue by jbravo94** [senaite/senaite.diagnosis#2]
Hi @xispa,

thanks for the release!
Just tested it out.

After adding senaite.diagnosis under the eggs section, i got following error after buildout:
![Screenshot_2024-01-15_22-46-04](https://github.com/senaite/senaite.diagnosis/assets/26746017/9cb61249-b2dc-470b-b306-acb08d841ca7)

looks like the pypi version misses the docs folder:
![Screenshot_2024-01-15_22-47-00](https://github.com/senaite/senaite.diagnosis/assets/26746017/3d6b43b8-9fb3-4bbd-9d58-34a7eb8ff680)

As a workaround i could use your github release zip
`wget https://github.com/senaite/senaite.diagnosis/archive/refs/tags/v1.0.0.zip -O /home/senaite/buildout-cache/downloads/dist/senaite.diagnosis-1.0.0.zip`

BR,
Johannes

**Comment by xispa** [comment]
Thanks for reporting @jbravo94 . We've released [`senaite.diagnosis` v1.0.1 at pypi](https://pypi.org/project/senaite.diagnosis/1.0.1/). It should be fine now.

**Comment by jbravo94** [comment]
Thanks, its working.
